
var animationDuration="0.8"
var borderWidth=" 4px "
var backgroundColor="white"
var borderContent=".border-content {position: absolute;width: 100%;height: 100%;top: 0%;left: 0%;}"
$.fn.borderContinuous=function borderContinuous(animationDuration,borderWidth,activeWhen,backgroundColor){var className="border-continuous"
$(this).wrapInner("<div class='border-content'></div>");$(this).append('<div class='+className+'><div></div><div></div><div></div><div></div></div>');$(this).children(".border-content").css({"padding":borderWidth});var timePerSide=animationDuration/4
$(this).children("."+className).children().css({"background-color":backgroundColor,});$(this).children("."+className).find(':first-child').css({"height":borderWidth,"width":"0%","-webkit-transition":"width"+timePerSide+"s linear "+timePerSide*0+"s","transition":"width "+timePerSide+"s linear "+timePerSide*0+"s",});$(this).children("."+className).find(':nth-child(2)').css({"width":borderWidth,"height":"0%","-webkit-transition":"height"+timePerSide+"s linear "+timePerSide*1+"s","transition":"height "+timePerSide+"s linear "+timePerSide*1+"s",});$(this).children("."+className).find(':nth-child(3)').css({"height":borderWidth,"width":"0%","-webkit-transition":"width"+timePerSide+"s linear "+timePerSide*2+"s","transition":"width "+timePerSide+"s linear "+timePerSide*2+"s",});$(this).children("."+className).find(':nth-child(4)').css({"width":borderWidth,"height":"0%","-webkit-transition":"height"+timePerSide+"s linear "+timePerSide*3+"s","transition":"height "+timePerSide+"s linear "+timePerSide*3+"s",});$(document.body).prepend("<style>."+className+".appear div:nth-child(4) {height: 100%;} ."+className+".appear div:nth-child(3) {width: 100%;} ."+className+".appear div:nth-child(2) {height: 100%;} ."+className+".appear div:first-child {width: 100%;} </style>");if(activeWhen=="inview"){$(this).bind('inview',function(event,visible){if(visible){$(this).children("."+className).find(':nth-child(odd)').css({"width":"100%",});$(this).children("."+className).find(':nth-child(even)').css({"height":"100%",});}else{$(this).children("."+className).find(':nth-child(odd)').css({"width":"0%",});$(this).children("."+className).find(':nth-child(even)').css({"height":"0%",});}});}
else{setTimeout(function()
{$(this).find(':last-child').addClass("appear");},300);}};$.fn.borderSimultaneous=function borderSimultaneous(animationDuration,borderWidth,activeWhen,backgroundColor){var className="border-simultaneous"
$(this).wrapInner("<div class='border-content'></div>");$(this).append('<div class='+className+'><div></div><div></div><div></div><div></div></div>');$(document.body).prepend("<!-- Sets padding for "+className+" on "+this+" --><style>.border-content { padding: "+borderWidth+";}");var timePerSide=animationDuration/2
$(this).children("."+className).children().css({"background-color":backgroundColor,});$(this).children("."+className).find(':first-child').css({"height":borderWidth,"width":"0%","-webkit-transition":"width"+timePerSide+"s linear "+timePerSide*0+"s","transition":"width "+timePerSide+"s linear "+timePerSide*0+"s",});$(this).children("."+className).find(':nth-child(2)').css({"width":borderWidth,"height":"0%","-webkit-transition":"height"+timePerSide+"s linear "+timePerSide*1+"s","transition":"height "+timePerSide+"s linear "+timePerSide*1+"s",});$(this).children("."+className).find(':nth-child(3)').css({"height":borderWidth,"width":"0%","-webkit-transition":"width"+timePerSide+"s linear "+timePerSide*0+"s","transition":"width "+timePerSide+"s linear "+timePerSide*0+"s",});$(this).children("."+className).find(':nth-child(4)').css({"width":borderWidth,"height":"0%","-webkit-transition":"height"+timePerSide+"s linear "+timePerSide*1+"s","transition":"height "+timePerSide+"s linear "+timePerSide*1+"s",});$(this).children(".border-content").css({"padding":borderWidth});if(activeWhen=="inview"){$(this).bind('inview',function(event,visible){if(visible){$(this).children("."+className).find(':nth-child(odd)').css({"width":"100%",});$(this).children("."+className).find(':nth-child(even)').css({"height":"100%",});}else{$(this).children("."+className).find(':nth-child(odd)').css({"width":"0%",});$(this).children("."+className).find(':nth-child(even)').css({"height":"0%",});}});}
else{setTimeout(function()
{$(this).find(':last-child').addClass("appear");},300);}};$.fn.line=function line(animationDuration,borderWidth,side,activeWhen,backgroundColor){var className="line"
var timePerSide=animationDuration
$(this).wrapInner("<div class='border-content'></div>");$(this).append('<div class='+className+'> <div></div> </div>');$(this).children("."+className).css({"-webkit-transition":"all "+timePerSide+"s linear "+timePerSide*0+"s","transition":"all "+timePerSide+"s linear "+timePerSide*0+"s","background-color":backgroundColor,});$(this).children(".border-content").css({"padding":borderWidth});switch(true){case side=="top":$(this).children(".line").css({"top":"0","left":"0","width":"0%","height":borderWidth,});break;case side=="right":$(this).children(".line").css({"bottom":"0","right":"0","height":"0%","width":borderWidth,});break;case side=="bottom":$(this).children(".line").css({"bottom":"0","left":"0","width":"0%","height":borderWidth,});break
case side=="left":$(this).children(".line").css({"bottom":"0","left":"0","height":"0%","width":borderWidth,});break}
if(activeWhen=="inview"){if(side=="left"||side=="right"){$(this).bind('inview',function(event,visible){if(visible){$(this).children(".line").css({"height":"100%",});}else{$(this).children(".line").css({"height":"0%",});}});}
else if(side=="top"||side=="bottom"){$(this).bind('inview',function(event,visible){if(visible){$(this).children(".line").css({"width":"100%",});}else{$(this).children(".line").css({"width":"0%",});}});}
else{alert("Make sure you have specified which side for the line function! In this case, the variable 'side' currently equals: "+side);}}
else{setTimeout(function()
{$('.'+className).addClass("appear");},300);}};(function(d){var p={},e,a,h=document,i=window,f=h.documentElement,j=d.expando;d.event.special.inview={add:function(a){p[a.guid+"-"+this[j]]={data:a,$element:d(this)}},remove:function(a){try{delete p[a.guid+"-"+this[j]]}catch(d){}}};d(i).bind("scroll resize",function(){e=a=null});!f.addEventListener&&f.attachEvent&&f.attachEvent("onfocusin",function(){a=null});setInterval(function(){var k=d(),j,n=0;d.each(p,function(a,b){var c=b.data.selector,d=b.$element;k=k.add(c?d.find(c):d)});if(j=k.length){var b;if(!(b=e)){var g={height:i.innerHeight,width:i.innerWidth};if(!g.height&&((b=h.compatMode)||!d.support.boxModel))b="CSS1Compat"===b?f:h.body,g={height:b.clientHeight,width:b.clientWidth};b=g}e=b;for(a=a||{top:i.pageYOffset||f.scrollTop||h.body.scrollTop,left:i.pageXOffset||f.scrollLeft||h.body.scrollLeft};n<j;n++)if(d.contains(f,k[n])){b=d(k[n]);var l=b.height(),m=b.width(),c=b.offset(),g=b.data("inview");if(!a||!e)break;c.top+l>a.top&&c.top<a.top+e.height&&c.left+m>a.left&&c.left<a.left+e.width?(m=a.left>c.left?"right":a.left+e.width<c.left+m?"left":"both",l=a.top>c.top?"bottom":a.top+e.height<c.top+l?"top":"both",c=m+"-"+l,(!g||g!==c)&&b.data("inview",c).trigger("inview",[!0,m,l])):g&&b.data("inview",!1).trigger("inview",[!1])}}},250)})(jQuery);